### PR TITLE
update to strong-deploy 3.0.0

### PR DESCRIPTION
**Pull request by Setogit**
connect to strongloop/strong-arc#582

### CODE REVIEW

**Comment by Setogit** [comment]
@slnode test please

**Comment by rmg** [comment]
Looks reasonable, but strongloop/strong-deploy#49 needs to be merged before this can be properly tested by CI.

**Comment by Setogit** [comment]
strongloop/strong-deploy#49 has been merged.

@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@Setogit looks like you triggered your rebuild before the merge had been fully pushed to staging. Looks like it is all passing now, though.

:shipit:

**Comment by Setogit** [comment]
@slnode test please

**Pull request merged**
